In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
df=pd.read_csv(r"D:\programming\models\dataset\train_grad.csv")
df.head()

id  Marital status  Application mode  Application order  Course  \
0   0               1                 1                  1    9238   
1   1               1                17                  1    9238   
2   2               1                17                  2    9254   
3   3               1                 1                  3    9500   
4   4               1                 1                  2    9500   

   Daytime/evening attendance  Previous qualification  \
0                           1                       1   
1                           1                       1   
2                           1                       1   
3                           1                       1   
4                           1                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  ...  \
0                           126.0            1                       1  ...   
1                           125.0            1                      19  ...   
2                           137.0            1                       3  ...   
3                           131.0            1                      19  ...   
4                           132.0            1                      19  ...   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    6   
1                                    0                                    6   
2                                    0                                    6   
3                                    0                                    8   
4                                    0                                    7   

   Curricular units 2nd sem (evaluations)  \
0                                       7   
1                                       9   
2                                       0   
3                                      11   
4                                      12   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    6                         12.428571   
1                                    0                          0.000000   
2                                    0                          0.000000   
3                                    7                         12.820000   
4                                    6                         12.933333   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               11.1   
1                                               0               11.1   
2                                               0               16.2   
3                                               0               11.1   
4                                               0                7.6   

   Inflation rate   GDP    Target  
0             0.6  2.02  Graduate  
1             0.6  2.02   Dropout  
2             0.3 -0.92   Dropout  
3             0.6  2.02  Enrolled  
4             2.6  0.32  Graduate  

[5 rows x 38 columns]

In [3]:
np.unique(df['Target'])

array(['Dropout', 'Enrolled', 'Graduate'], dtype=object)

In [4]:
df.select_dtypes('object')

Target
0      Graduate
1       Dropout
2       Dropout
3      Enrolled
4      Graduate
...         ...
76513  Graduate
76514  Graduate
76515  Enrolled
76516   Dropout
76517  Graduate

[76518 rows x 1 columns]

In [5]:
from sklearn.preprocessing import LabelEncoder
lr=LabelEncoder()
df['Target']=lr.fit_transform(df['Target'])
lr.classes_

array(['Dropout', 'Enrolled', 'Graduate'], dtype=object)

In [6]:
df.isnull().sum()

id                                                0
Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance                        0
Previous qualification                            0
Previous qualification (grade)                    0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Admission grade                                   0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship 

In [8]:
x=df.iloc[:,1:-1].values
y=df.iloc[:,-1].values
print(x.shape,y.shape)

(76518, 36) (76518,)


In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [10]:
print(x)

[[-0.25343684 -0.90242254 -0.52406561 ... -0.15841825 -0.44910992
   0.93317583]
 [-0.25343684  0.05668196 -0.52406561 ... -0.15841825 -0.44910992
   0.93317583]
 [-0.25343684  0.05668196  0.28918253 ...  1.7636745  -0.66357837
  -0.37269756]
 ...
 [ 8.80317976  0.05668196 -0.52406561 ... -0.79911583 -1.44996265
  -1.34988173]
 [-0.25343684 -0.90242254  1.10243066 ... -1.47750151  0.98067968
   0.17807897]
 [-0.25343684 -0.90242254 -0.52406561 ...  1.49985785  1.12365864
  -1.76740587]]


In [11]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=64,activation='relu'))
ann.add(tf.keras.layers.Dense(units=128,activation='relu'))
ann.add(tf.keras.layers.Dense(units=256,activation='relu'))
ann.add(tf.keras.layers.Dense(units=3,activation='softmax'))
ann.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=[['accuracy']])
ann.fit(x,y,epochs=250,batch_size=32)

Epoch 1/250
2392/2392 [==============================] - 8s 2ms/step - loss: 0.4865 - accuracy: 0.8113
Epoch 2/250
2392/2392 [==============================] - 5s 2ms/step - loss: 0.4633 - accuracy: 0.8210
Epoch 3/250
2392/2392 [==============================] - 5s 2ms/step - loss: 0.4584 - accuracy: 0.8212
Epoch 4/250
2392/2392 [==============================] - 5s 2ms/step - loss: 0.4537 - accuracy: 0.8244
Epoch 5/250
2392/2392 [==============================] - 5s 2ms/step - loss: 0.4501 - accuracy: 0.8250
Epoch 6/250
2392/2392 [==============================] - 5s 2ms/step - loss: 0.4464 - accuracy: 0.8269
Epoch 7/250
2392/2392 [==============================] - 5s 2ms/step - loss: 0.4431 - accuracy: 0.8290
Epoch 8/250
2392/2392 [==============================] - 6s 2ms/step - loss: 0.4387 - accuracy: 0.8297
Epoch 9/250
2392/2392 [==============================] - 6s 2ms/step - loss: 0.4362 - accuracy: 0.8301
Epoch 10/250
2392/2392 [==============================] - 6s 2ms/step - l

In [101]:
test_df=pd.read_csv(r"D:\programming\models\dataset\test_grad.csv",index_col=False)


In [129]:
test_df.isnull().sum()

id                                                0
Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance                        0
Previous qualification                            0
Previous qualification (grade)                    0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Admission grade                                   0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship 

In [103]:

val=test_df.iloc[:,1:].values
val=sc.transform(val)

In [122]:
y_pred=ann.predict(val)
print(y_pred)

1595/1595 [==============================] - 2s 1ms/step
[[9.9995935e-01 4.0604409e-05 2.1907775e-13]
 [1.5966311e-12 5.8418420e-05 9.9994159e-01]
 [5.2928017e-06 2.7029814e-02 9.7296482e-01]
 ...
 [9.9293536e-01 7.0482376e-04 6.3597024e-03]
 [1.0000000e+00 4.9828566e-14 9.1443511e-12]
 [8.0010623e-01 1.2364418e-07 1.9989374e-01]]


In [123]:
y_pred=np.argmax(y_pred,axis=1)
y_pred

array([0, 2, 2, ..., 0, 0, 0], dtype=int64)

In [124]:
y_pred=pd.DataFrame(y_pred)
print(y_pred)

       0
0      0
1      2
2      2
3      0
4      1
...   ..
51007  0
51008  0
51009  0
51010  0
51011  0

[51012 rows x 1 columns]


In [125]:
y_pred=y_pred.replace(0,'Dropout')
y_pred=y_pred.replace(1,'Enrolled')
y_pred=y_pred.replace(2,'Graduate')
print(y_pred)

              0
0       Dropout
1      Graduate
2      Graduate
3       Dropout
4      Enrolled
...         ...
51007   Dropout
51008   Dropout
51009   Dropout
51010   Dropout
51011   Dropout

[51012 rows x 1 columns]


In [126]:
frame = [test_df[['id']], y_pred]
ans_df = pd.concat(frame, axis=1) 


In [128]:
ans_df.to_csv("grad_ans.csv",index=False)